const ContactActionTypes = {
  TOGGLE_SUBMIT_BUTTON_FORM_CLICK: 'TOGGLE_SUBMIT_BUTTON_FORM_CLICK',
  TOGGLE_TYPE_FILL_FORM_CLICK: 'TOGGLE_TYPE_FILL_FORM_CLICK',
  TOGGLE_TYPE_SUBMIT_FORM_CLICK: 'TOGGLE_TYPE_SUBMIT_FORM_CLICK',
  POST_FORM_CONTACT_START: 'POST_FORM_CONTACT_START',
  POST_FORM_CONTACT_SUCCESS: 'POST_FORM_CONTACT_SUCCESS',
  POST_FORM_CONTACT_FAILURE: 'POST_FORM_CONTACT_FAILURE',
};

export default ContactActionTypes;
