const ContactActionTypes = {
  TOGGLE_SUBMIT_BUTTON_FORM_CLICK: "TOGGLE_SUBMIT_BUTTON_FORM_CLICK",
  TOGGLE_TYPE_FILL_FORM_CLICK: "TOGGLE_TYPE_FILL_FORM_CLICK",
  TOGGLE_TYPE_SUBMIT_FORM_CLICK: "TOGGLE_TYPE_SUBMIT_FORM_CLICK",
};

export default ContactActionTypes;
