const AboutActionTypes = {
  SUMMARY_TOGGLE_VIBRATE: "SUMMARY_TOGGLE_VIBRATE",
  SUMMARY_TOGGLE_DOWNLOAD: "SUMMARY_TOGGLE_DOWNLOAD",
  PAGE_DROPDOWN_HIDDEN: "PAGE_DROPDOWN_HIDDEN",
  TIMELINE_CAREER_YEAR_2016_CLICK: "TIMELINE_CAREER_YEAR_2016_CLICK ",
  TIMELINE_CAREER_YEAR_2017_CLICK: "TIMELINE_CAREER_YEAR_2017_CLICK ",
  TIMELINE_CAREER_YEAR_2018_CLICK: "TIMELINE_CAREER_YEAR_2018_CLICK ",
  TIMELINE_CAREER_YEAR_2019_CLICK: "TIMELINE_CAREER_YEAR_2019_CLICK ",
  TIMELINE_CAREER_YEAR_CURRENT_CLICK: "TIMELINE_CAREER_YEAR_CURRENT_CLICK ",
};

export default AboutActionTypes;
