const CollectionActionTypes = {
  FETCH_COLLECTION_LIST: "FETCH_COLLECTION_LIST",
  FETCH_COLLECTION_LIST_SUCCESS: "FETCH_COLLECTION_LIST_SUCCESS",
  FETCH_LOAD_MORE_COLLECTION: "FETCH_LOAD_MORE_COLLECTION",
  FETCH_LOAD_MORE_COLLECTION_SUCCESS: "FETCH_LOAD_MORE_COLLECTION_SUCCESS",
  FETCH_COLLECTION_LIST_FINISHED: "FETCH_COLLECTION_LIST_FINISHED",
};

export default CollectionActionTypes;
