const CollectionActionTypes = {
  FETCH_COLLECTION_LIST: 'FETCH_COLLECTION_LIST',
  FETCH_COLLECTION_LIST_SUCCESS: 'FETCH_COLLECTION_LIST_SUCCESS',
  FETCH_LOAD_MORE_COLLECTION: 'FETCH_LOAD_MORE_COLLECTION',
  FETCH_LOAD_MORE_COLLECTION_SUCCESS: 'FETCH_LOAD_MORE_COLLECTION_SUCCESS',
  FETCH_COLLECTION_LIST_FINISHED: 'FETCH_COLLECTION_LIST_FINISHED',
  TOGGLE_WEBSITE_LINK_DROPDOWN: 'TOGGLE_WEBSITE_LINK_DROPDOWN',
  SET_CURRENT_WEBSITE_PATHNAME: 'SET_CURRENT_WEBSITE_PATHNAME',
};

export default CollectionActionTypes;
